steps:
  - name: node:lts
    entrypoint: npm
    args:
      - install
      - --only=production
  - name: node:lts
    entrypoint: npm
    args:
      - run-script
      - build
    env:
      - "GATSBY_GOOGLE_ANALYTICS_TRACKING_ID=$_GATSBY_GOOGLE_ANALYTICS_TRACKING_ID"
  - name: "gcr.io/$PROJECT_ID/firebase"
    args:
      - deploy
      - --only
      - hosting
    secretEnv: ["FIREBASE_TOKEN"]
secrets:
  - kmsKeyName: "projects/my-projects-804b4/locations/global/keyRings/cloudbuilder/cryptoKeys/firebase-token"
    secretEnv:
      FIREBASE_TOKEN: "CiQAGkuahIuSpvGrVIiYPdYHANmcl8pgZQFOO33QowBdG6Gs/IQSawDci3UvBwfC1GIpbl+h5mlWQXiJTLFU40/aWKGgMolQarr+ELHYM9fpI5Ufh4AXFcebUC30SWneI8XZcxR47bV7vNUsGJVhNHKX83IKK14cNlDVttshFVzDausQJ9hB4HYbzjN+XHHraJkC"
tags: ["cloud-builders-community"]
